version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_DB: flight-db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - ./flight_planner/db:/docker-entrypoint-initdb.d
    networks:
      - postgres_network

  app:
    #    image: flight-planner:latest
    build: .
    container_name: flight-app
    ports:
      - "5001:5000"
    environment:
      POSTGRES_HOST: postgres-db
      POSTGRES_DB: flight-db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    depends_on:
      - db
    networks:
      - postgres_network

networks:
  postgres_network:
